### ISSUE TITLE
How to store color styles at runtime?

### ISSUE THREAD

**Issue by real-felix** [RustyYato/colorize#2]
I tried to use `Style`, but because of the type state, every different style is a different type. `dyn Colorize` is not possible, because that trait cannot be made into an object.

**Comment by RustyYato** [comment]
If you need to do it at runtime, you can use [`Style::into_runtime_style`](https://docs.rs/colorz/latest/colorz/struct.Style.html#method.into_runtime_style) and in a const context [`Style::const_into_runtime_style`](https://docs.rs/colorz/latest/colorz/struct.Style.html#method.const_into_runtime_style).

Both return a common `Style` type which is easy to use at runtime

Maybe it would be good to highlight this in the type docs 🤔
