### ISSUE TITLE
error[E0554]: `#![feature]` may not be used on the stable release channel

### ISSUE THREAD

**Issue by slyshykO** [RustyYato/colorize#3]
--> C:\Users\alex\.cargo\registry\src\index.crates.io-6f17d22bba15001f\colorz-1.1.3\src/lib.rs:3:1
  |
3 | #![feature(rustdoc_missing_doc_code_examples)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `colorz` (lib) due to 1 previous error

---------------
Win11
rustc 1.82.0 (f6e511eec 2024-10-15)

**Comment by RustyYato** [comment]
Ah, sorry about that! That was a mistake, I'll have a fixed release up today

**Comment by RustyYato** [comment]
This is fixed in version 1.1.4!
